const races =  [
  {
    title: "Bahrain",
    startDate: "2023-03-03",
    endDate: "2023-03-05",
    round: 1,
    laps: 57,
    raceName: "Formula 1 Gulf Air Bahrain Grand Prix 2023",
    trackName: "Bahrain International Circuit",
    countryCode: "bh",
    km: 5.412,
    trackFile: "bahrain.svg",
    customStartWeight: 72,
    customEndWeight: 52,
  },
  {
    title: "Saudi Arabia",
    startDate: "2023-03-17",
    endDate: "2023-03-19",
    round: 2,
    laps: 50,
    raceName: "Formula 1 STC Saudi Arabian Grand Prix 2023",
    trackName: "Jeddah Corniche Circuit",
    countryCode: "sa",
    km: 6.174,
    trackFile: "saudi-arabia.svg",
    customStartWeight: 45,
    customEndWeight: 37
  },
  {
    title: "Australia",
    startDate: "2023-03-31",
    endDate: "2023-04-02",
    round: 3,
    laps: 58,
    raceName: "Formula 1 Rolex Australian Grand Prix 2023",
    trackName: "Albert Park Circuit",
    countryCode: "au",
    km: 5.278,
    trackFile: "australia.svg",
    customMapWidth: 51,
    customStartWeight: 58,
    customEndWeight: 37,
  },
  {
    title: "Azerbaijan",
    startDate: "2023-04-28",
    endDate: "2023-04-30",
    round: 4,
    laps: 51,
    raceName: "Formula 1 Azerbaijan Grand Prix 2023",
    trackName: "Baku City Circuit",
    countryCode: "az",
    km: 6.003,
    trackFile: "azerbaijan.svg",
    customMapWidth: 51,
    customStartWeight: 52,
    customEndWeight: 33,
  },
  {
    title: "Miami",
    startDate: "2023-05-05",
    endDate: "2023-05-07",
    round: 5,
    laps: 57,
    raceName: "Formula 1 Crypto.com Miami Grand Prix 2023",
    trackName: "Miami International Autodrome",
    countryCode: "us",
    km: 5.412,
    trackFile: "miami.svg",
    customStartWeight: 108,
    customEndWeight: 61,
    customMapWidth: 56,
  },
  {
    title: "Emilia-Romagna",
    startDate: "2023-05-19",
    endDate: "2023-05-21",
    round: 6,
    laps: 63,
    raceName: "Formula 1 Qatar Airways Gran Premio del Made in Italy e Dell’Emila-Romagna 2023",
    trackName: "Autodromo Enzo e Dino Ferrari",
    countryCode: "it",
    km: 4.909,
    trackFile: "emilia.svg",
    customStartWeight: 37,
    customEndWeight: 25,
    customMapWidth: 45,
  },
  {
    title: "Monaco",
    startDate: "2023-05-26",
    endDate: "2023-05-28",
    round: 7,
    laps: 78,
    raceName: "Formula 1 Grand Prix de Monaco 2023",
    trackName: "Circuit de Monaco",
    countryCode: "mc",
    km: 3.337,
    trackFile: "monaco.svg",
    customMapWidth: 35,
    customStartWeight: 75,
    customEndWeight: 48,
    customMapWidth: 45,
  },
  {
    title: "Spain",
    startDate: "2023-06-02",
    endDate: "2023-06-04",
    round: 8,
    laps: 66,
    raceName: "Formula 1 AWS Grand Premio de España 2023",
    trackName: "Circuit de Barcelona-Catalunya",
    countryCode: "es",
    km: 4.675,
    trackFile: "spain.svg",
    customMapWidth: 45,
    customStartWeight: 109,
    customEndWeight: 71,
  },
  {
    title: "Canada",
    startDate: "2023-06-16",
    endDate: "2023-06-18",
    round: 9,
    laps: 70,
    raceName: "Formula 1 Pirelli Grand Prix du Canada 2023",
    trackName: "Circuit Gilles-Villeneuve",
    countryCode: "ca",
    km: 4.361,
    trackFile: "canada.svg",
    customMapWidth: 52,
    customStartWeight: 78,
    customEndWeight: 52,
  },
  {
    title: "Austria",
    startDate: "2023-06-30",
    endDate: "2023-07-02",
    round: 10,
    laps: 71,
    raceName: "Formula 1 Grosser Preis von Österreich 2023",
    trackName: "Red Bull Ring",
    countryCode: "at",
    km: 4.318,
    trackFile: "austria.svg",
    customStartWeight: 74,
    customEndWeight: 57,
  },
  {
    title: "Great Britain",
    startDate: "2023-07-07",
    endDate: "2023-07-09",
    round: 11,
    laps: 52,
    raceName: "Formula 1 Aramco British Grand Prix 2023",
    trackName: "Silverstone Circuit",
    trackFile: "britain.svg",
    countryCode: "gb",
    km: 5.891,
    customStartWeight: 44,
    customEndWeight: 30,
  },
  {
    title: "Hungary",
    startDate: "2023-07-21",
    endDate: "2023-07-23",
    round: 12,
    laps: 70,
    raceName: "Formula 1 Qatar Airways Hungarian Grand Prix 2023",
    trackName: "Hungaroring",
    countryCode: "hu",
    km: 4.381,
    trackFile: "hungary.svg",
    customStartWeight: 67,
    customEndWeight: 54,
  },
  {
    title: "Belgium",
    startDate: "2023-07-28",
    endDate: "2023-07-30",
    round: 13,
    laps: 44,
    raceName: "Formula 1 Belgian Grand Prix 2023",
    trackName: "Circuit de Spa-Francorchamps",
    countryCode: "be",
    km: 7.004,
    trackFile: "belgium.svg",
    customStartWeight: 74,
    customEndWeight: 54,
    customMapWidth: 47,
  },
  {
    title: "Netherlands",
    startDate: "2023-08-25",
    endDate: "2023-08-27",
    round: 14,
    laps: 72,
    raceName: "Formula 1 Heineken Dutch Grand Prix 2023",
    trackName: "Circuit Zandvoort",
    countryCode: "nl",
    km: 4.259,
    trackFile: "netherlands.svg",
    customStartWeight: 46,
    customEndWeight: 35,
  },
  {
    title: "Italy",
    startDate: "2023-09-01",
    endDate: "2023-09-03",
    round: 15,
    laps: 53,
    raceName: "Formula 1 Pirelli Gran Premio d’Italia 2023",
    trackName: "Autodromo Nazionale Monza",
    countryCode: "it",
    km: 5.793,
    trackFile: "italy.svg",
    customStartWeight: 126,
    customEndWeight: 80,
    customMapWidth:45,
  },
  {
    title: "Singapore",
    startDate: "2023-09-15",
    endDate: "2023-09-17",
    round: 16,
    laps: 61,
    raceName: "Formula 1 Singapore Airlines Singapore Grand Prix 2023",
    trackName: "Marina Bay Street Circuit",
    countryCode: "sg",
    km: 5.063,
    trackFile: "singapore.svg",
    customStartWeight: 56,
    customEndWeight: 33,
    customMapWidth: 45,
  },
  {
    title: "Japan",
    startDate: "2023-09-22",
    endDate: "2023-09-24",
    round: 17,
    laps: 53,
    raceName: "Formula 1 Lenovo Japanese Grand Prix 2023",
    trackName: "Suzuka International Racing Course",
    countryCode: "jp",
    km: 5.807,
    trackFile: "japan.svg",
    customStartWeight: 96,
    customEndWeight: 84,
    customMapWidth: 45,
  },
  {
    title: "Qatar",
    startDate: "2023-10-06",
    endDate: "2023-10-08",
    round: 18,
    laps: 57,
    raceName: "Formula 1 Qatar Airways Grand Prix 2023",
    trackName: "Lusail International Circuit",
    countryCode: "qa",
    km: 5.418,
    trackFile: "qatar.svg",
    customStartWeight: 100,
    customEndWeight: 78,
  },
  {
    title: "United States",
    startDate: "2023-10-20",
    endDate: "2023-10-22",
    round: 19,
    laps: 56,
    raceName: "Formula 1 Lenovo United States Grand Prix 2023",
    trackName: "Circuit of the Americas",
    countryCode: "us",
    km: 5.513,
    trackFile: "unitedstates.svg",
    customStartWeight: 44,
    customEndWeight: 30,
  },
  {
    title: "Mexico",
    startDate: "2023-10-27",
    endDate: "2023-10-29",
    round: 20,
    laps: 71,
    raceName: "Formula 1 Gran Premio de la Ciudad de México 2023",
    trackName: "Autódromo Hermanos Rodríguez",
    countryCode: "mx",
    km: 4.304,
    trackFile: "mexico.svg",
    customStartWeight: 85,
    customEndWeight: 62,
  },
  {
    title: "Brazil",
    startDate: "2023-11-03",
    endDate: "2023-11-05",
    round: 21,
    laps: 71,
    raceName: "Formula 1 Rolex Grande Prêmio de São Paulo 2023",
    trackName: "Autódromo José Carlos Pace",
    countryCode: "br",
    km: 4.309,
    trackFile: "brazil.svg",
    customStartWeight: 91,
    customEndWeight: 68,
  },
  {
    title: "Las Vegas",
    startDate: "2023-11-16",
    endDate: "2023-11-18",
    round: 22,
    laps: 50,
    raceName: "Formula 1 Heineken Silver Las Vegas Grand Prix 2023",
    trackName: "Las Vegas Strip Circuit",
    countryCode: "us",
    km: 6.120,
    trackFile: "lasvegas.svg",
    customStartWeight: 61,
    customEndWeight: 43,
  },
  {
    title: "Abu Dhabi",
    startDate: "2023-11-24",
    endDate: "2023-11-26",
    round: 23,
    laps: 58,
    raceName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2023",
    trackName: "Yas Marina Circuit",
    countryCode: "ae",
    km: 5.281,
    trackFile: "abudhabi.svg",
    customStartWeight: 60,
    customEndWeight: 33,
    customMapWidth: 50,
  }
];
